// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/example.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	mi := &file_internal_proto_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_internal_proto_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_proto_example_proto protoreflect.FileDescriptor

const file_internal_proto_example_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/example.proto\"\x1e\n" +
	"\bHelloReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\" \n" +
	"\n" +
	"HelloReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name22\n" +
	"\aGreeter\x12'\n" +
	"\rSayHelloAgain\x12\t.HelloReq\x1a\v.HelloReplyB4Z2github.com/vsespontanno/gochat-grpc/internal/protob\x06proto3"

var (
	file_internal_proto_example_proto_rawDescOnce sync.Once
	file_internal_proto_example_proto_rawDescData []byte
)

func file_internal_proto_example_proto_rawDescGZIP() []byte {
	file_internal_proto_example_proto_rawDescOnce.Do(func() {
		file_internal_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_example_proto_rawDesc), len(file_internal_proto_example_proto_rawDesc)))
	})
	return file_internal_proto_example_proto_rawDescData
}

var file_internal_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_example_proto_goTypes = []any{
	(*HelloReq)(nil),   // 0: HelloReq
	(*HelloReply)(nil), // 1: HelloReply
}
var file_internal_proto_example_proto_depIdxs = []int32{
	0, // 0: Greeter.SayHelloAgain:input_type -> HelloReq
	1, // 1: Greeter.SayHelloAgain:output_type -> HelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_example_proto_init() }
func file_internal_proto_example_proto_init() {
	if File_internal_proto_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_example_proto_rawDesc), len(file_internal_proto_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_example_proto_goTypes,
		DependencyIndexes: file_internal_proto_example_proto_depIdxs,
		MessageInfos:      file_internal_proto_example_proto_msgTypes,
	}.Build()
	File_internal_proto_example_proto = out.File
	file_internal_proto_example_proto_goTypes = nil
	file_internal_proto_example_proto_depIdxs = nil
}
